=== OpenSyndrome/schema/schemas/v1/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Open Syndrome Case Definition Schema",
  "type": "object",
  "additionalProperties": false,
  "$defs": {
    "criterion": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Type of criterion.\n\n- criteria: Group of criteria or conditions.\n- syndrome: Syndrome (defined by another definition, but used here as a criterion).\n- symptom: just a symptom.\n- diagnosis: The diagnosed disease, which may or may not be followed by a code, e.g. ICD.\n- diagnostic_test: Tests or medical examinations to confirm a diagnosis, e.g. gluplasma glucose.\n- professional_judgment: Professional assessment.\n- epidemiological_history: Travel history or contact with someone with an epidemiological link.\n- demographic_criteria: Factors such as age or sex.",
          "enum": [
            "criterion",
            "syndrome",
            "symptom",
            "diagnosis",
            "diagnostic_test",
            "professional_judgment",
            "epidemiological_history",
            "demographic_criteria"
          ]
        },
        "logical_operator": {
          "type": "string",
          "description": "Keywords that represent a logical operation on criteria.\n\nAND: All conditions in this group must be satisfied (true).\nOR: At least one condition in this group must be satisfied.\nAT_LEAST: Used with the number specified in `logical_operator_arguments`. At least that many conditions must be true.",
          "enum": [
            "AND",
            "OR",
            "AT_LEAST"
          ]
        },
        "logical_operator_arguments": {
          "type": "array",
          "description": "Used with `logical_operator = AT_LEAST`. At least that many conditions must be true.",
          "items": {
            "type": "integer"
          },
          "minItems": 1,
          "maxItems": 1
        },
        "name": {
          "type": "string",
          "description": "Criterion label."
        },
        "attribute": {
          "type": "string",
          "description": "The referred attribute.",
          "examples": ["body_temperature", "age", "onset"]
        },
        "value": {
          "description": "The reference value for the referred attribute. It has no type because it could be anything.",
          "examples": [true, 37.5, "abnormal but non-specific bowel gas pattern"]
        },
        "description": {
          "type": "string",
          "description": "A detailed description of the criterion."
        },
        "ontology_id": {
          "type": "string",
          "description": "The compacted identifier from an ontology e.g. HP:0002615 for Hypotension",
          "examples": ["hpo:0002045", "mondo:0020674"]
        },
        "operator": {
          "description": "Comparison operators.\n\n>: Value must be greater than the specified threshold.\n>=: Value must be greater than or equal to the specified threshold.\n<: Value must be less than the specified threshold.\n<=: Value must be less than or equal to the specified threshold.\n==: Value must exactly match the specified value.\n!=: Value must not match the specified value.\nregex: Value must match the specified regular expression pattern.",
          "type": "string",
          "enum": [
            ">",
            ">=",
            "<",
            "<=",
            "==",
            "!=",
            "regex"
          ]
        },
        "regex_pattern": {
          "type": "string",
          "description": "Regular expression for evaluation and pattern matching.",
          "examples": ["deng[u]?e"]
        },
        "regex_flags": {
          "description": "Regular expression flags for extra configuration.",
          "type": "string",
          "pattern": "^[gimsuy]*$",
          "examples": ["i"]
        },
        "code": {
          "type": "object",
          "description": "System agnostic diagnosis code.",
          "properties": {
            "system": {
              "type": "string",
              "description": "The diagnosis system used.",
              "examples": ["ICD-10", "SNOMED-CT"]
            },
            "code": {
              "type": "string",
              "examples": ["J11", "A.99", "233604007"]
            },
            "display": {
              "type": "string",
              "description": "A label that represents this code.",
              "examples": ["Pneumonia", "Dengue"]
            }
          },
          "required": [
            "system",
            "code"
          ]
        },
        "values": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/criterion"
          }
        }
      },
      "required": [
        "type"
      ],
      "anyOf": [
        {
          "required": [
            "name"
          ]
        },
        {
          "required": [
            "values"
          ]
        }
      ]
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri",
      "description": "URI pointing to the JSON Schema that validates this document. Enables machine-readable schema discovery and validation by standard JSON Schema tools.",
      "examples": ["https://opensyndrome.org/schema/v1/schema.json"]
    },
    "@context": {
      "description": "JSON-LD context mapping.",
      "anyOf": [
        { "type": "string" },
        { "type": "object" },
        { "type": "array" }
      ]
    },
    "@type": {
      "type": "string",
      "description": "Semantic class.",
      "enum": [
        "osd:CaseDefinition",
        "osd:SyndromeDefinition"
      ]
    },
    "id": {
      "type": "string",
      "format": "uri",
      "description": "Unique ID from Open Syndrome Initiative.",
      "examples": ["https://opensyndrome.org/definitions/fa02718a-e203-4e31-a30b-9456789aaea0"]
    },
    "title": {
      "type": "string",
      "description": "Title of the case definition."
    },
    "description": {
      "type": "string",
      "description": "Detailed description of a case definition."
    },
    "scope": {
      "type": "string",
      "enum": [
        "specific",
        "broad"
      ],
      "description": "A broad definition aims to capture most or all true cases, while a specific definition provides a more accurate description but risks missing some true cases."
    },
    "category": {
      "type": "string",
      "enum": [
        "confirmed",
        "probable",
        "suspected"
      ],
      "default": "suspected",
      "description": "Case definition categories according to Bassil, K. (2008). Case definition. In Encyclopedia of epidemiology (Vol. 2, pp. 133-134). SAGE Publications, Inc., https://doi.org/10.4135/9781412953948"
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "description": "Case definition version to be defined by the author but following the Semantic Versioning Specification (https://semver.org/)."
    },
    "open_syndrome_version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "description": "Open Syndrome Definition schema version.",
      "examples": ["1.0.0"]
    },
    "published_in": {
      "type": "string",
      "format": "uri",
      "description": "URL where the narrative format definition was originally published or can be found."
    },
    "created_at": {
      "type": "string",
      "format": "date",
      "description": "Date of creation.",
      "examples": ["2020-05-30"]
    },
    "published_at": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time of publication at Open Syndrome Initiative website (UTC).",
      "examples": ["2020-05-30T12:00:00Z"]
    },
    "published_by": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of the case definition publishers in the Open Syndrome Initiative.",
      "examples": [["Ana Maria Braga"], ["Oswaldo Gonçalves Cruz", "Bento Gonçalves Cruz", "Amália Taborda de Bulhões Cruz"]]
    },
    "location": {
      "type": "string",
      "description": "Free text for location input; recommended format is 'City, State/Region, Country' following geographical hierarchy with comma separation",
      "examples": ["Salvador, Bahia, Brasil", "Berlin, Germany", "Nigeria"]
    },
    "language": {
      "type": "string",
      "description": "Written language",
      "examples": ["English", "Brazilian Portuguese"]
    },
    "organization": {
      "type": "string",
      "description": "The organization responsible for this case definition maintenance.",
      "examples": ["Ministry of Health", "The Epidemic Intelligence from Open Sources Initiative"]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "People or organizations that authored this case definition.",
      "examples": [["Ana Maria Braga"], ["Oswaldo Gonçalves Cruz", "Bento Gonçalves Cruz", "Amália Taborda de Bulhões Cruz"]]
    },
    "inclusion_criteria": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/criterion"
      }
    },
    "exclusion_criteria": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/criterion"
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Any notes that may be relevant to this case definition."
    },
    "references": {
      "description": "References which have supported this definition followed by a URL.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "citation": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "url"
        ]
      }
    },
    "status": {
      "type": "string",
      "description": "Current status of this definition in the Open Syndrome Initiative platform.",
      "enum": [
        "draft",
        "published",
        "deprecated"
      ],
      "default": "draft"
    },
    "keywords": {
      "description": "Keywords related to a definition.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "examples": ["outbreaks", "covid19", "WHO"]
    },
    "human_readable_definition": {
      "type": "string",
      "description": "A human-readable definition of the case definition, which can be used for display purposes in user interfaces."
    },
    "surveillance_system_type": {
      "type": "string",
      "description": "The type of surveillance system the definition was designed for or is used for."
    },
    "target_public_health_threats": {
        "type": "array",
        "description": "List of public health threats that this case definition targets.",
        "items": {
            "type": "string",
            "examples": ["COVID-19", "Influenza", "Extreme Weather Events"]
        }
    },
    "definition_type": {
      "type": "string",
      "description": "Type of the definition",
      "enum": [
        "case_definition",
        "syndrome_definition"
      ],
      "default": "case_definition"
    }
  },
  "required": [
    "title",
    "scope",
    "category",
    "version",
    "open_syndrome_version",
    "published_in",
    "published_at",
    "location",
    "language",
    "organization",
    "inclusion_criteria",
    "references",
    "status",
    "definition_type"
  ]
}

=== OpenSyndrome/schema/bin/extremetemperaturesheat_argentina_jsonld.json
{
  "id": "https://opensyndrome.org/definitions/extremetemperaturesheat_argentina_1.0.0",
  "@type": "osd:CaseDefinition",
  "title": "Heat Exposure",
  "description": "Case definition for suspected heat exposure in individuals with history of extreme heat exposure during Early Temperature Extreme Alert by National Meteorological Service, and clinical symptoms attributable to high body temperature (39°C or higher) and 2 or more of the following: sweating, nausea/vomiting, hypotension, tachycardia, tachypnea, altered consciousness, seizures, fainting. In infants: excessive sweating, irritated skin due to sweating.",
  "scope": "specific",
  "category": "suspected",
  "version": "1.0.0",
  "open_syndrome_version": "1.0.0",
  "location": "Argentina",
  "language": "English",
  "organization": "Ministerio de Salud",
  "inclusion_criteria": [
    {
      "type": "criterion",
      "logical_operator": "AND",
      "values": [
        {
          "type": "symptom",
          "name": "High body temperature",
          "attribute": "body_temperature",
          "operator": ">=",
          "value": 39,
          "description": "Temperature measured in celsius",
          "ontology_id": "hpo:0002045"
        },
        {
          "type": "criterion",
          "logical_operator": "AT_LEAST",
          "logical_operator_arguments": [
            2
          ],
          "values": [
            {
              "type": "symptom",
              "name": "Warm skin",
              "ontology_id": "hpo:0032506"
            },
            {
              "type": "symptom",
              "name": "Sweating",
              "ontology_id": "hpo:0000975"
            },
            {
              "type": "symptom",
              "name": "Nausea/vomiting",
              "ontology_id": "hpo:0002017"
            },
            {
              "type": "symptom",
              "name": "Hypotension",
              "ontology_id": "hpo:0002615"
            },
            {
              "type": "symptom",
              "name": "Tachycardia",
              "ontology_id": "hpo:0001649"
            },
            {
              "type": "symptom",
              "name": "Tachypnea",
              "ontology_id": "hpo:0002789"
            },
            {
              "type": "symptom",
              "name": "Altered consciousness",
              "ontology_id": "hpo:0004372"
            },
            {
              "type": "symptom",
              "name": "Seizures",
              "ontology_id": "hpo:0001250"
            },
            {
              "type": "symptom",
              "name": "Fainting",
              "ontology_id": "hpo:0001279"
            },
            {
              "type": "symptom",
              "name": "Excessive sweating (infants)",
              "description": "Irritated skin due to sweating (infants)",
              "ontology_id": "hpo:0000975"
            }
          ]
        }
      ]
    }
  ],
  "published_in": "https://opensyndrome.org",
  "published_at": "2025-02-08T12:20:55Z",
  "published_by": [
    "Open Syndrome Initiative"
  ],
  "notes": [
    "ICD-10 code HEAT: X30 (Exposure to excessive natural heat), T67 (Effects of heat and light)"
  ],
  "references": [
    {
      "url": "https://www.argentina.gob.ar/sites/default/files/2019/10/msal-manual_de_normas_y_procedimientos_de_vigilancia_y_control_de_eno_2022.pdf"
    }
  ],
  "status": "draft",
  "human_readable_definition": "Toda persona con antecedentes de\nexposición a calor extremo en circunstancia de Alerta Temprana por Temperatura\nExtrema (calor) del Servicio Meteorológico Nacional, y sintomatología clínica\natribuible - Temperatura corporal mayor o igual a 39 ºC y 2 o más de los siguientes\nsíntomas, a saber:\nSignos y síntomas atribuibles: piel caliente, sudoración abundante en un primer\nmomento o escasa, náuseas y/o vómitos, hipotensión, taquicardia y taquipnea,\nalteración del estado de conciencia, convulsiones, desmayo. En bebés: sudoración\nabundante, piel irritada por sudor.",
  "target_public_health_threats": [
    "Heat",
    "mondo:0020674"
  ],
  "keywords": [
    "Heat",
    "South America",
    "Climate-related"
  ],
  "definition_type": "case_definition",
  "@context": "https://opensyndrome.org/schema/v1/context.jsonld"
}
